"""move profile to userrooms

Revision ID: 6bc75b890bd8
Revises: e96b853b1d26
Create Date: 2024-12-03 12:14:05.972767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6bc75b890bd8'
down_revision: Union[str, None] = 'e96b853b1d26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_room', sa.Column('profile', sa.JSON(), nullable=False))
    op.drop_column('users', 'profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('user_room', 'profile')
    # ### end Alembic commands ###
