"""move profile to userrooms

Revision ID: f72add2e389e
Revises: 6bc75b890bd8
Create Date: 2024-12-03 12:17:59.346883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72add2e389e'
down_revision: Union[str, None] = '6bc75b890bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_room', sa.Column('user_gift_to_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_room', 'users', ['user_gift_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_room', type_='foreignkey')
    op.drop_column('user_room', 'user_gift_to_id')
    # ### end Alembic commands ###
